services:
  - type: web
    name: social-sphere-backend
    rootDir: backend
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run build && if [ -f social-sphere.tar.gz ]; then mkdir -p .tmp && tar -xzf social-sphere.tar.gz -C .tmp && pnpm strapi import -f .tmp/export_*.tar.gz --force && rm -rf .tmp; fi
    startCommand: pnpm run start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: social-sphere-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true

databases:
  - name: social-sphere-db
    plan: free
