services:
  - type: web
    name: social-sphere-backend
    rootDir: backend
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: social-sphere-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
    # Add preDeployCommand to handle the specific file
    preDeployCommand: |
      if [ -f social-sphere.tar.gz ]; then
        echo "Found export file, starting import process..."
        mkdir -p .tmp
        tar -xzf social-sphere.tar.gz -C .tmp
        echo "Extracted archive, starting Strapi import..."
        yarn strapi import -f .tmp/export_*.tar.gz --force
        if [ $? -eq 0 ]; then
          echo "Import completed successfully"
        else
          echo "Import failed"
          exit 1
        fi
        rm -rf .tmp
      else
        echo "No export file found named social-sphere.tar.gz"
      fi
databases:
  - name: social-sphere-db
    plan: free
